/// Flutter icons BarberIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BarberIcon
///      fonts:
///       - asset: fonts/BarberIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BarberIcon {
  BarberIcon._();

  static const _kFontFam = 'BarberIcon';

  static const IconData barbero = IconData(0xe800, fontFamily: _kFontFam);
}
